services:
  docker-astro-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - .:/app
